# Basics Of NumPy 

Numpy is the fundamental package for scientific computing with Python.
1) A powerful N-dimensional array object

2) Sophisticated functions


Source : https://numpy.org/



In [7]:
#importing numpy library
import numpy as np

In [3]:
#check vesrion of numpy library 
np.__version__

'1.20.1'

In [ ]:
l1=

In [4]:
#create a numpy array
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

# Single Dimensional Array creating in NumPy :

In [2]:
import numpy as np
#single dimensional array
n1=np.array([1,2,3,4,5])

In [3]:
n1

array([1, 2, 3, 4, 5])

# Multi-dimensinal array creating in NumPy :

In [10]:
#multi-dimensinal array
n2=np.array([[1,2,3,4,5],[6,7,8,9]])


<ipython-input-10-bfc7fae4918d>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  n2=np.array([[1,2,3,4,5],[6,7,8,9]])


In [9]:
#print array n2
n2

array([list([1, 2, 3, 4, 5]), list([6, 7, 8, 9])], dtype=object)

In [11]:
#print datatype of array n2
type(n2)

numpy.ndarray

# Initialzing NumPy array with zeros :

In [12]:
n3=np.zeros((1,2))
#np.zeros((row,column))
n3

array([[0., 0.]])

In [13]:
n4=np.zeros((5,5))
#np.zeros((row,column))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Initialzing NumPy array with same number :

In [14]:
n5=np.full((2,2),10)
#np.full((row,column),number with initialize)
n5

array([[10, 10],
       [10, 10]])

# Initailzing NumPy array within a range :

In [15]:
n6=np.arange(10,20)
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
n7=np.arange(10,50,5)
n7

array([10, 15, 20, 25, 30, 35, 40, 45])

# Initialzing NumPy array with random numbers

In [22]:
n8=np.random.randint(1,50,5)
#np.random.randint(Start point,end point,number of intergers select random)
n8

array([28, 13, 38, 21, 39])

# Checking the shape of NumPy array

In [24]:
n9=np.array([[1,2,4],[5,6,7]])
n9.shape

(2, 3)

In [25]:
#before changing shape of array -2-Row and 3 Column
n9

array([[1, 2, 4],
       [5, 6, 7]])

In [26]:
# Change the shape of array 
n9.shape=(3,2)
n9.shape

(3, 2)

In [27]:
#before changing shape of array -3-Row and 2 Column
n9

array([[1, 2],
       [4, 5],
       [6, 7]])

# Joining NumPy Arrays


# 1.Vertical Stack   - vstack()

In [29]:
a1=np.array([10,20,30])
a2=np.array([40,50,60])
np.vstack((a1,a2))

array([[10, 20, 30],
       [40, 50, 60]])

# 2.Horizontal Stack - hstack()

In [30]:
#same above example
np.hstack((a1,a2))

array([10, 20, 30, 40, 50, 60])

# 3.Column stack  - column_stack()

In [31]:
np.column_stack((a1,a2))

array([[10, 40],
       [20, 50],
       [30, 60]])

# NumPy Intersection & Difference 

In [32]:
# Intersection 
b1=np.array([10,20,30,40,50,60,70])
b2=np.array([30,40,50,60,70,80,90])
np.intersect1d(b1,b2)

array([30, 40, 50, 60, 70])

In [34]:
# Difference (b1,b2)
np.setdiff1d(b1,b2)

array([10, 20])

In [35]:
# Difference (b2,b1)
np.setdiff1d(b2,b1)

array([80, 90])

# Addition of NumPy Arrays

In [36]:
b3=np.array([30,40])
b4=np.array([20,30])
np.sum([b3,b4])

120

In [37]:
# column-wise addition set axis=0
np.sum([b3,b4],axis=0)

array([50, 70])

In [38]:
# Row-wise addition set axis=1
np.sum([b3,b4],axis=1)

array([70, 50])

# NumPy array Mathematics 

In [39]:
#Basic Addition
d1=np.array([10,20,30,40])
d1=d1+1
d1

array([11, 21, 31, 41])

In [40]:
#Basic Subtraction
d1=np.array([10,20,30,40])
d1=d1-2
d1

array([ 8, 18, 28, 38])

In [41]:
#Basic Multiplication
d1=np.array([10,20,30,40])
d1=d1*2
d1

array([20, 40, 60, 80])

In [42]:
#Basic Division
d1=np.array([10,20,30,40])
d1=d1/5
d1

array([2., 4., 6., 8.])

# NumPy Math Functions 

In [44]:
b4=np.array([10,20,30,40,50,60,70,80])

In [45]:
# Calculate mean of array b4
np.mean(b4)

45.0

In [46]:
#Standard Deviation
np.std(b4)

22.9128784747792

In [47]:
#Median 
np.median(b4)

45.0

# NumPy Save and Load 

In [48]:
#Saving NumPy Array
d2=np.array([10,20,30,40,50])
np.save("My_NumPy",d2)

In [49]:
# Load NumPy Array 
m1=np.load("My_NumPy.npy")
m1

array([10, 20, 30, 40, 50])

### Difference between NumPy array and python list with example

###### Python list 

In [3]:
l1=[1,2,3,'4',5,True]
l1

[1, 2, 3, '4', 5, True]

##### NumPy array

In [8]:
# if we add an element of string data type in a numpy array
# then it will upcast the data type to string of all the elements.
l2=np.array([1,2,3,'4',5,True])
l2

array(['1', '2', '3', '4', '5', 'True'], dtype='<U11')

##### Difference between numpy array and lis
 1. Datatype should be same of all elements in a numpy whereas it can be different in case if lists.
 

##### Now, we will create list and numpy array and apply a very basic function of multiplication by 2. we will see that in case of list the elements are duplicated and appended to the list whereas in case of numpy array where all elements are multiplied by 2.

In [15]:
l1

[1, 2, 3, '4', 5, True]

In [14]:
# l1 list multiplied by 2 and see the result.
l1*2

[1, 2, 3, '4', 5, True, 1, 2, 3, '4', 5, True]

In [16]:
# Broadcasting Operation 
# m2 list multiplied by 2 and see the result.
m2=np.array([1,2,3,4,5])
m2+2

array([3, 4, 5, 6, 7])

### Create a matrix in NumPy 

In [17]:
# first create a list and pass the list in numpy array.
p1=([1,2,3],
   [4,5,6],
   [7,8,9])

In [18]:
p1

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [19]:
a1=np.array(p1)

In [20]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
# Access elements of matrix 
a1[0][1] #a1[row][column]

2

In [25]:
# create a 3X3 array of random integers in the interval(0,10)
np.random.randint(1,10,(3,3))

array([[3, 6, 1],
       [3, 6, 6],
       [3, 3, 7]])

#### We got a different matrix when we generated another random matrix. We can get the same matrix again by fixing the seed. let's see how?

In [28]:
#fixing the seed 
np.random.seed(0)
np.random.randint(0,10,(3,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

##### Create a matrix of "Ones" of specific dimension.

In [31]:
# create matrix 
np.ones((4,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

##### Create a indetity matrix 

In [32]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])